export const components = [
  {
    type: 'ServerChasis',
    name: 'Chasis 1U',
    price: 250,
    maintenanceCost: 5.0, // Costo de mantenimiento USD/mes
    estimatedConsumption: 25, // Consumo en vatios (W)
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Chasis para servidores de 1U de altura.',
    isSelled: false,
    modelPath: './assets/models/chasis.glb', // Ruta del modelo 3D
  },
  {
    type: 'CPU',
    name: 'Intel Xeon E5-2690',
    price: 1500,
    maintenanceCost: 15.0,
    estimatedConsumption: 120,
    compatibleList: ['Placa Base 1'],
    details: 'CPU de alto rendimiento para servidores.',
    isSelled: false,
    modelPath: './assets/models/cpu.glb',
  },
  {
    type: 'RAM',
    name: 'DDR4 32GB',
    price: 300,
    maintenanceCost: 2.5,
    estimatedConsumption: 10,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Módulo de memoria RAM de 32GB.',
    isSelled: false,
    modelPath: './assets/models/ram.glb',
  },
  {
    type: 'HardDisk',
    name: 'SSD 1TB',
    price: 100,
    maintenanceCost: 1.0,
    estimatedConsumption: 5,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Disco de estado sólido de 1TB.',
    isSelled: false,
    modelPath: './assets/models/ssd.glb',
  },
  {
    type: 'BiosConfig',
    name: 'BIOS Standard',
    price: 50,
    maintenanceCost: 0.5,
    estimatedConsumption: 1,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Configuración de BIOS estándar.',
    isSelled: false,
    modelPath: './assets/models/bios.glb',
  },
  {
    type: 'Fan',
    name: 'Ventilador 80mm',
    price: 15,
    maintenanceCost: 0.2,
    estimatedConsumption: 2,
    compatibleList: ['Chasis 1U', 'Chasis 2U'],
    details: 'Ventilador de 80mm para refrigeración.',
    isSelled: false,
    modelPath: './assets/models/fan.glb',
  },
  {
    type: 'PowerSupply',
    name: 'Fuente 500W',
    price: 75,
    maintenanceCost: 0.8,
    estimatedConsumption: 50,
    compatibleList: ['Chasis 1U', 'Chasis 2U'],
    details: 'Fuente de alimentación de 500W.',
    isSelled: false,
    modelPath: './assets/models/psu.glb',
  },
  {
    type: 'GPU',
    name: 'NVIDIA A100',
    price: 5000,
    maintenanceCost: 50.0,
    estimatedConsumption: 300,
    compatibleList: ['Placa Base 1'],
    details: 'GPU de alto rendimiento para cargas de trabajo de IA.',
    isSelled: false,
    modelPath: './assets/models/gpu.glb',
  },
  {
    type: 'MotherBoard',
    name: 'Placa Base 1',
    price: 400,
    maintenanceCost: 5.0,
    estimatedConsumption: 30,
    compatibleList: ['Intel Xeon E5-2690', 'DDR4 32GB', 'SSD 1TB', 'BIOS Standard', 'NVIDIA A100'],
    details: 'Placa base compatible con el chasis 1U.',
    isSelled: false,
    modelPath: './assets/models/motherboard.glb',
  },
  {
    type: 'NetworkInterface',
    name: 'Tarjeta de Red 10G',
    price: 150,
    maintenanceCost: 1.5,
    estimatedConsumption: 8,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Interfaz de red con capacidad de 10 Gigabit.',
    isSelled: false,
    modelPath: './assets/models/nic.glb', // Modelo para Network Interface Card
  },
  {
    type: 'OS',
    name: 'Ubuntu Server 22.04 LTS',
    price: 0, // Licencia gratuita/open source
    maintenanceCost: 0.5,
    estimatedConsumption: 0,
    compatibleList: ['Intel Xeon E5-2690'], // Asume compatibilidad con la CPU
    details: 'Sistema Operativo de servidor Linux, estable y de largo soporte.',
    isSelled: false,
    modelPath: './assets/models/os.glb',
  },
];