export const components = [
  {
    type: 'Chasis',
    name: 'Chasis 1U',
    cost: 250,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Chasis para servidores de 1U de altura.',
    selled: false,
  },
  {
    type: 'CPU',
    name: 'Intel Xeon E5-2690',
    cost: 1500,
    compatibleList: ['Placa Base 1'],
    details: 'CPU de alto rendimiento para servidores.',
    selled: false,
  },
  {
    type: 'RAM',
    name: 'DDR4 32GB',
    cost: 300,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Módulo de memoria RAM de 32GB.',
    selled: false,
  },
  {
    type: 'HardDisk',
    name: 'SSD 1TB',
    cost: 100,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Disco de estado sólido de 1TB.',
    selled: false,
  },
  {
    type: 'BiosConfig',
    name: 'BIOS Standard',
    cost: 50,
    compatibleList: ['Placa Base 1', 'Placa Base 2'],
    details: 'Configuración de BIOS estándar.',
    selled: false,
  },
  {
    type: 'Fan',
    name: 'Ventilador 80mm',
    cost: 15,
    compatibleList: ['Chasis 1U', 'Chasis 2U'],
    details: 'Ventilador de 80mm para refrigeración.',
    selled: false,
  },
  {
    type: 'PowerSupply',
    name: 'Fuente 500W',
    cost: 75,
    compatibleList: ['Chasis 1U', 'Chasis 2U'],
    details: 'Fuente de alimentación de 500W.',
    selled: false,
  },
  {
    type: 'GPU',
    name: 'NVIDIA A100',
    cost: 5000,
    compatibleList: ['Placa Base 1'],
    details: 'GPU de alto rendimiento para cargas de trabajo de IA.',
    selled: false,
  },
  // Componentes adicionales para compatibilidad
  {
    type: 'Placa Base',
    name: 'Placa Base 1',
    cost: 400,
    compatibleList: ['Intel Xeon E5-2690', 'DDR4 32GB', 'SSD 1TB', 'BIOS Standard', 'NVIDIA A100'],
    details: 'Placa base compatible con el chasis 1U.',
    selled: false,
  }
];